from __future__ import annotations

from pathlib import Path
import subprocess
import sys


AUTONOMY_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = AUTONOMY_ROOT.parent
VENV_PYTHON = AUTONOMY_ROOT / ".venv" / "Scripts" / "python.exe"
OUTPUT_PATH = REPO_ROOT / "artifacts" / "runtime_checks" / "latest.md"


def _run(command: list[str]) -> tuple[int, str]:
    completed = subprocess.run(command, capture_output=True, text=True, check=False)
    output = completed.stdout.strip() or completed.stderr.strip()
    return completed.returncode, _normalize(output)


def _normalize(text: str) -> str:
    filtered_lines = [
        line for line in text.replace("\x00", "").splitlines() if "screen size is bogus" not in line
    ]
    return "\n".join(filtered_lines).strip()


def _wsl_path(path: Path) -> str:
    drive = path.drive.rstrip(":").lower()
    tail = path.as_posix().split(":", maxsplit=1)[-1].lstrip("/")
    return f"/mnt/{drive}/{tail}"


def _run_wsl(command: str) -> tuple[int, str]:
    return _run(["wsl", "bash", "-lc", command])


def _venv_module_status(module_name: str) -> str:
    if not VENV_PYTHON.exists():
        return "venv_missing"
    code = (
        "import importlib.util; "
        f"print('yes' if importlib.util.find_spec('{module_name}') else 'no')"
    )
    rc, output = _run([str(VENV_PYTHON), "-c", code])
    if rc != 0:
        return f"error: {output}"
    return output


def _markdown_value(value: str) -> str:
    return (value or "-").replace("|", "/").replace("\n", "<br>")


def main() -> None:
    checks: list[tuple[str, str]] = []
    px4_repo = REPO_ROOT / "vendor" / "PX4-Autopilot"
    px4_repo_wsl = _wsl_path(px4_repo)
    px4_build_wsl = f"{px4_repo_wsl}/build/px4_sitl_default"
    px4_binary_wsl = f"{px4_build_wsl}/bin/px4"

    checks.append(("venv_python", "present" if VENV_PYTHON.exists() else "missing"))
    checks.append(("venv_mavsdk", _venv_module_status("mavsdk")))

    rc, output = _run(["wsl", "-l", "-v"])
    checks.append(("wsl_available", "yes" if rc == 0 else "no"))
    if rc == 0:
        distro_rc, distro_output = _run_wsl("printf '%s' \"$WSL_DISTRO_NAME\"")
        kernel_rc, kernel_output = _run_wsl("uname -r")
        checks.append(("wsl_active_distro", distro_output if distro_rc == 0 else "unknown"))
        checks.append(("wsl_kernel", kernel_output if kernel_rc == 0 else "unknown"))

    rc, output = _run_wsl("python3 --version")
    checks.append(("wsl_python", output if rc == 0 else "unavailable"))

    rc, output = _run_wsl("make --version | head -n 1")
    checks.append(("wsl_make", output if rc == 0 else "unavailable"))

    rc, output = _run_wsl("cmake --version | head -n 1")
    checks.append(("wsl_cmake", output if rc == 0 else "unavailable"))

    rc, output = _run_wsl("ninja --version | head -n 1")
    checks.append(("wsl_ninja", output if rc == 0 else "unavailable"))

    rc, output = _run_wsl(
        f"if [ -d '{px4_repo_wsl}' ]; then echo present; else echo missing; fi"
    )
    checks.append(("px4_repo_in_wsl", output if rc == 0 else "unknown"))

    rc, output = _run_wsl(
        f"if [ -d '{px4_build_wsl}' ]; then echo present; else echo missing; fi"
    )
    checks.append(("px4_build_dir", output if rc == 0 else "unknown"))

    rc, output = _run_wsl(
        f"if [ -d '{px4_build_wsl}' ]; then "
        f"cd '{px4_build_wsl}' && "
        "ninja -t targets all | grep -E '(^px4:|/px4:)' | head -n 1; "
        "else echo build_dir_missing; fi"
    )
    if rc == 0 and output:
        checks.append(("px4_target_status", "present"))
    else:
        checks.append(("px4_target_status", output or "missing"))

    rc, output = _run_wsl(
        f"if [ -x '{px4_binary_wsl}' ]; then "
        f"stat -c 'present size=%s mtime=%y' '{px4_binary_wsl}'; "
        "else echo missing; fi"
    )
    checks.append(("px4_binary_status", output if rc == 0 else "unknown"))

    rc, output = _run_wsl(
        "processes=$(pgrep -af '(^|/)ninja( |$)|/px4( |$)|gz sim' | head -n 10); "
        "if [ -n \"$processes\" ]; then printf '%s\n' \"$processes\"; else echo idle; fi"
    )
    checks.append(("px4_runtime_processes", output if rc == 0 else "unknown"))

    rc, output = _run_wsl(
        "if command -v gz >/dev/null 2>&1; then echo harmonic; "
        "elif command -v gazebo >/dev/null 2>&1; then echo gazebo-classic-installed; "
        "else echo not_installed; fi"
    )
    checks.append(("gazebo_status", output if rc == 0 else "unknown"))

    rc, output = _run_wsl("if command -v gz >/dev/null 2>&1; then gz sim --versions | head -n 1; fi")
    checks.append(("gazebo_version", output if rc == 0 and output else "unknown"))

    lines = [
        "# Runtime Readiness Report",
        "",
        "Generated by `autonomy/scripts/check_runtime_readiness.py`.",
        "",
        "| Check | Result |",
        "| --- | --- |",
    ]
    for name, value in checks:
        lines.append(f"| {name} | {_markdown_value(value)} |")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Runtime readiness report written to: {OUTPUT_PATH}")


if __name__ == "__main__":
    sys.exit(main())
