lr0: [1.0e-05, 1.0e-03]
lrf: [0.01, 0.2]
momentum: [0.88, 0.98]
weight_decay: [0.0001, 0.001]
warmup_epochs: [1.0, 5.0]
box: [5.0, 12.0]
cls: [0.5, 2.0]
dfl: [0.8, 2.0]
hsv_h: [0.0, 0.05]
hsv_s: [0.2, 0.9]
hsv_v: [0.1, 0.6]
degrees: [0.0, 20.0]
translate: [0.0, 0.2]
scale: [0.2, 0.8]
shear: [0.0, 5.0]
perspective: [0.0, 0.001]
fliplr: [0.0, 0.5]
mosaic: [0.0, 1.0]
mixup: [0.0, 0.3]
copy_paste: [0.0, 0.4]
close_mosaic: [0.0, 10.0]
